### ISSUE TITLE
Setup Kafka for Even Stream Processing

### ISSUE THREAD

**Issue by skabbass1** [SoftwareEngineeringDaily/sedaily-event-stream#1]
1) Setup an initial Kafka  producer consumer configuration
2) Set up  event topics and partitions
3) Setup docker / ansible  to install and setup sedaily-event-stream kafka instance automagically for
    local testing. This will help new contributors get started quickly rather than worry too much about 
   installation and setup of the Kafka cluster

**Comment by andrewmarklloyd** [comment]
[This project](https://github.com/wurstmeister/kafka-docker) was really easy to get a local Kafka instance running

**Comment by skabbass1** [comment]
Awsome. I will try it out and close this issue.

**Comment by andrewmarklloyd** [comment]
We're looking into using Redis Streams at this point

**Comment by andrewmarklloyd** [comment]
No longer using Kafka so I'm closing
