### ISSUE TITLE
Enhancements to event payload schema

### ISSUE THREAD

**Issue by skabbass1** [SoftwareEngineeringDaily/sedaily-event-stream#15]
I think We would need to add another attribute, ```eventData``` to our  ```event``` object. ```EventData``` will be an object containing metadata  specific to the event being fired.  This metadata will have  its own schema which we would need to validate.  
For example, when say a ```pause_episode``` event is fired, the  ```eventData``` attribute  of our ```event``` object  would be an object with attributes such  as  ```minutes_remaining``` , ```minutes_playes```, ```episode_name``` etc.  Following is a crude example
```javascript
event: {
      body: {
        clientId: Joi.string().required(),
       deviceType: Joi.string().required(),
       deviceType: Joi.string().required().valid(['iOS', 'Android', 'Browser']),
        location: Joi.string().required(),
       eventTime: Joi.string().required(),
       eventType: Joi.string().required()
       eventTime: Joi.date().timestamp('unix').required(),
       eventType: Joi.string().required().valid(
         [
           'login',
           'logout',
           'play_episode',
           'pause_episode',
           'like_episode',
           'completed_episode'
        ],
       eventData: Joi.object()
)

pauseEpisodeEvent: {
episodeName: Joi.string().required(),
minutesPlayed: Joi.number().required(),
minutesRemaining: Joi.number().required()
}

```
With this, we will end up doing a two a step validation: (1) Validate the top level event  schema (2) Based on the eventType, validate the eventData schema. 

What are your thoughts?  Perhaps there is a way to avoid the two step validation? .

**Comment by andrewmarklloyd** [comment]
I actually had this same thought yesterday. You're right we need to validate each event type. This looks like a good way to go. Do we even need to validate further? Like querying the MongoDB to see if the episode name is even valid?

**Comment by skabbass1** [comment]
I dont think we need to  do event data content validation  on  the gateway service side.  Essentially, we will have various consumers consuming events from the event stream and these consumers could do the extra  content validation they need.  In this way we keep the gateway service light and simple and only limited to validating the  schematic structure of the event payload.

We could even write a consumer process whose sole job is to read events from a "channel"  or "topic"  on  the event stream, validate the content of these events and then re-publish the validated events on a different "channel" or "topic"  to be consumed by other downstream consumers

**Comment by andrewmarklloyd** [comment]
That makes sense, keep it light
