### ISSUE TITLE
Setup build and testing environment

### ISSUE THREAD

**Issue by skabbass1** [SoftwareEngineeringDaily/sedaily-event-stream#7]
We need set up a testing and build environment for the sedaily-event-stream API (issue #3 ) and Gateway service ( issue #5 ) . The environment needs to be consistent with that already in use by the existing sedaily backend service

**Comment by andrewmarklloyd** [comment]
Is this requirement referring to the production and test environments, or just locally? If locally I believe we can close it since we have a containerized setup

**Comment by skabbass1** [comment]
Locally. You are right , I will close. Thanks
